#!/bin/bash
# 2015-02-12, Aurelio Jargas
#
# Generate the functions list YAML datafile.

gitroot='../../funcoeszz'
out='list.yml'

cd $(dirname "$0")

> $out  # truncate
echo "########### DO NOT EDIT -- NÃO EDITE ###########" >> $out
echo "########### Generated by $(basename $0) ###########" >> $out
echo >> $out

ZZCOR=0 ZZOFF= ZZDIR=$gitroot/zz $gitroot/funcoeszz zzajuda --lista |
	sed '
		# Escapes
		s/\\/\\\\/g
		s/"/\\"/g

		# zzfoo   Foo bar. ===> zzfoo: "Foo bar."
		s/  */:& "/
		s/$/"/
	' >> $out
echo "$PWD/$out done."
